//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CityTireAndAutoEntities : DbContext
    {
        public CityTireAndAutoEntities()
            : base("name=CityTireAndAutoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_customer_list> tbl_customer_list { get; set; }
        public virtual DbSet<tbl_employee> tbl_employee { get; set; }
        public virtual DbSet<tbl_employee_credentials> tbl_employee_credentials { get; set; }
        public virtual DbSet<tbl_treadtracker_barcode> tbl_treadtracker_barcode { get; set; }
        public virtual DbSet<tbl_treadtracker_workorder> tbl_treadtracker_workorder { get; set; }
        public virtual DbSet<tbl_treadtracker_casing_brands> tbl_treadtracker_casing_brands { get; set; }
        public virtual DbSet<tbl_treadtracker_casing_sizes> tbl_treadtracker_casing_sizes { get; set; }
        public virtual DbSet<tbl_treadtracker_treads> tbl_treadtracker_treads { get; set; }
        public virtual DbSet<tbl_employee_attendance> tbl_employee_attendance { get; set; }
        public virtual DbSet<tbl_employee_personal> tbl_employee_personal { get; set; }
        public virtual DbSet<tbl_employee_payroll_biweekly> tbl_employee_payroll_biweekly { get; set; }
        public virtual DbSet<tbl_employee_payroll_dates> tbl_employee_payroll_dates { get; set; }
        public virtual DbSet<tbl_employee_payroll_summary> tbl_employee_payroll_summary { get; set; }
        public virtual DbSet<tbl_payroll_category_selection> tbl_payroll_category_selection { get; set; }
        public virtual DbSet<tbl_vehicle_info> tbl_vehicle_info { get; set; }
        public virtual DbSet<tbl_fuel_log> tbl_fuel_log { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<tbl_sehub_access> tbl_sehub_access { get; set; }
    }
}
