//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tire_adjustment
    {
        public string Tire_Adjustment_id { get; set; }
        public string cta_employee_name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string location_id { get; set; }
        public string non_sig_number { get; set; }
        public string replacement_invoice { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string postal_code { get; set; }
        public string brand { get; set; }
        public string tread { get; set; }
        public string size { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> current_EDL { get; set; }
        public Nullable<int> original_32nds { get; set; }
        public string manufacture_approval { get; set; }
        public Nullable<double> modified_adjustment_modified { get; set; }
        public Nullable<int> mileage_warranty { get; set; }
        public Nullable<int> average_tire_mileage { get; set; }
        public Nullable<double> modified_adjustment_mileage { get; set; }
        public string dot_0 { get; set; }
        public string product_code_0 { get; set; }
        public Nullable<int> thirty_seconds_0 { get; set; }
        public Nullable<int> mileage_0 { get; set; }
        public Nullable<double> percent_worn_0 { get; set; }
        public Nullable<double> repl_cost_0 { get; set; }
        public string reason_for_removal_0 { get; set; }
        public string dot_1 { get; set; }
        public string product_code_1 { get; set; }
        public Nullable<int> thirty_seconds_1 { get; set; }
        public Nullable<int> mileage_1 { get; set; }
        public Nullable<double> percent_worn_1 { get; set; }
        public Nullable<double> repl_cost_1 { get; set; }
        public string reason_for_removal_1 { get; set; }
        public string dot_2 { get; set; }
        public string product_code_2 { get; set; }
        public Nullable<int> thirty_seconds_2 { get; set; }
        public Nullable<int> mileage_2 { get; set; }
        public Nullable<double> percent_worn_2 { get; set; }
        public Nullable<double> repl_cost_2 { get; set; }
        public string reason_for_removal_2 { get; set; }
        public string dot_3 { get; set; }
        public string product_code_3 { get; set; }
        public Nullable<int> thirty_seconds_3 { get; set; }
        public Nullable<int> mileage_3 { get; set; }
        public Nullable<double> percent_worn_3 { get; set; }
        public Nullable<double> repl_cost_3 { get; set; }
        public string reason_for_removal_3 { get; set; }
        public string dot_4 { get; set; }
        public string product_code_4 { get; set; }
        public Nullable<int> thirty_seconds_4 { get; set; }
        public Nullable<int> mileage_4 { get; set; }
        public Nullable<double> percent_worn_4 { get; set; }
        public Nullable<double> repl_cost_4 { get; set; }
        public string reason_for_removal_4 { get; set; }
        public string dot_5 { get; set; }
        public string product_code_5 { get; set; }
        public Nullable<int> thirty_seconds_5 { get; set; }
        public Nullable<int> mileage_5 { get; set; }
        public Nullable<double> percent_worn_5 { get; set; }
        public Nullable<double> repl_cost_5 { get; set; }
        public string reason_for_removal_5 { get; set; }
        public string additional_comments { get; set; }
        public string original_purchase_invoice { get; set; }
    }
}
