//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_storyBoard_posts
    {
        public string post_id { get; set; }
        public string category { get; set; }
        public string subject { get; set; }
        public string details { get; set; }
        public Nullable<int> auther { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string loc_id { get; set; }
        public string attachment_name { get; set; }
        public string attachment_url { get; set; }
    }
}
