//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_treadtracker_production_log
    {
        public string barcode { get; set; }
        public string work_station { get; set; }
        public System.DateTime timestamp { get; set; }
        public string status { get; set; }
        public string details { get; set; }
    }
}
