//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee_attendance_bck
    {
        public string rfid_number { get; set; }
        public bool at_work { get; set; }
        public string at_work_location { get; set; }
        public Nullable<int> employee_id { get; set; }
    }
}
