//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_harpoon_devices
    {
        public string serial_number { get; set; }
        public string client_id { get; set; }
        public string location_zone { get; set; }
        public string display_color { get; set; }
        public string IP_address { get; set; }
        public string software_version { get; set; }
        public Nullable<int> auto_loc_id { get; set; }
        public Nullable<System.DateTime> time_stamp { get; set; }
        public string board_id { get; set; }
    }
}
