//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tread_tracker_customers
    {
        public string customer_number { get; set; }
        public string reporting_contact { get; set; }
        public string reporting_email { get; set; }
        public string default_retread { get; set; }
    }
}
