//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_payroll_submission_corporate
    {
        public string submission_id { get; set; }
        public string submitter_name { get; set; }
        public Nullable<int> submitter_empId { get; set; }
        public Nullable<System.DateTime> submission_date { get; set; }
        public Nullable<int> payroll_id { get; set; }
        public string location_id { get; set; }
    }
}
