//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee_personal
    {
        public int employee_id { get; set; }
        public string personal_email { get; set; }
        public string primary_phone { get; set; }
        public string secondary_phone { get; set; }
        public string home_street1 { get; set; }
        public string home_street2 { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string postal_code { get; set; }
        public string country { get; set; }
        public string emergency_contact_name { get; set; }
        public string emergency_contact_number { get; set; }
        public string employee_start_date { get; set; }
    }
}
