//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_source_labour_rates
    {
        public string loc_id { get; set; }
        public string part_number { get; set; }
        public Nullable<double> unit_price { get; set; }
        public string rate { get; set; }
    }
}
