//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_treadtracker_chamber_production
    {
        public string production_id { get; set; }
        public string envelope_id { get; set; }
        public string barcode { get; set; }
        public Nullable<int> position { get; set; }
        public string customer_name { get; set; }
        public string tread { get; set; }
        public string size { get; set; }
    }
}
