//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_attendance_log
    {
        public string loc_id { get; set; }
        public int employee_id { get; set; }
        public string event_id { get; set; }
        public System.DateTime time_stamp { get; set; }
    }
}
