//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_treadtracker_inventory_treadRubber
    {
        public string Part_number { get; set; }
        public Nullable<double> Quantity_lbs { get; set; }
        public string Tread { get; set; }
        public string Width { get; set; }
    }
}
