//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_payroll_employee_paystubs
    {
        public int emp_id { get; set; }
        public int payroll_id { get; set; }
        public Nullable<double> hours_worked { get; set; }
        public Nullable<double> gross_earnings { get; set; }
        public Nullable<double> federal_tax { get; set; }
        public Nullable<double> provincial_tax { get; set; }
        public Nullable<double> cpp { get; set; }
        public Nullable<double> ei { get; set; }
        public Nullable<double> group_ins { get; set; }
        public Nullable<double> rrsp { get; set; }
        public Nullable<double> total_deduction { get; set; }
        public Nullable<double> net_pay { get; set; }
    }
}
