//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_expense_claim
    {
        public string transaction_number { get; set; }
        public string empid { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public string supplier_name { get; set; }
        public string exp_account { get; set; }
        public string exp_description { get; set; }
        public string loc_id { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> hst { get; set; }
    }
}
