//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_source_commercial_tire_manufacturers
    {
        public string manufacturers { get; set; }
        public Nullable<int> tread_tracker { get; set; }
        public Nullable<int> fleetTVT { get; set; }
        public byte[] brand_image { get; set; }
    }
}
