//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_treadtracker_workorder_bck_20200412
    {
        public string retread_workorder { get; set; }
        public string customer_number { get; set; }
        public string employee_Id { get; set; }
        public string loc_Id { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string comments { get; set; }
    }
}
