//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_harpoon_clients
    {
        public string client_id { get; set; }
        public string client_name { get; set; }
        public string client_address1 { get; set; }
        public string client_address2 { get; set; }
        public string client_city { get; set; }
        public string client_province { get; set; }
        public string client_postal { get; set; }
        public string client_country { get; set; }
        public string client_phone { get; set; }
        public string client_fax { get; set; }
        public string client_email { get; set; }
        public string client_website { get; set; }
        public byte[] client_logo { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<bool> employees_page { get; set; }
        public Nullable<bool> fleet_page { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<bool> timesheet { get; set; }
    }
}
