//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_harpoon_settings_schedule
    {
        public string client_id { get; set; }
        public Nullable<int> sunday_open { get; set; }
        public string sunday_start { get; set; }
        public string sunday_end { get; set; }
        public string monday_saturday { get; set; }
    }
}
