//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_treadtracker_barcode
    {
        public string barcode { get; set; }
        public string retread_workorder { get; set; }
        public Nullable<int> line_number { get; set; }
        public Nullable<int> line_code { get; set; }
        public string serial_dot { get; set; }
        public string casing_size { get; set; }
        public string casing_brand { get; set; }
        public string retread_design { get; set; }
        public string unit_ID { get; set; }
        public string preliminary_inspection_result { get; set; }
        public Nullable<System.DateTime> preliminary_inspection_date { get; set; }
        public string ndt_machine_result { get; set; }
        public Nullable<System.DateTime> ndt_machine_date { get; set; }
        public string buffer_builder_result { get; set; }
        public Nullable<System.DateTime> buffer_builder_date { get; set; }
        public string final_inspection_result { get; set; }
        public Nullable<System.DateTime> final_inspection_date { get; set; }
        public string ship_to_location { get; set; }
        public Nullable<int> virgin { get; set; }
        public string comments { get; set; }
        public string TT050_result { get; set; }
        public Nullable<System.DateTime> TT050_date { get; set; }
        public string TT100_result { get; set; }
        public Nullable<System.DateTime> TT100_date { get; set; }
        public string TT200_result { get; set; }
        public Nullable<System.DateTime> TT200_date { get; set; }
        public string TT300_result { get; set; }
        public Nullable<System.DateTime> TT300_date { get; set; }
        public string TT400_result { get; set; }
        public Nullable<System.DateTime> TT400_date { get; set; }
        public string TT500_result { get; set; }
        public Nullable<System.DateTime> TT500_date { get; set; }
        public string TT600_result { get; set; }
        public Nullable<System.DateTime> TT600_date { get; set; }
    }
}
