//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tools_decibel_meter
    {
        public System.DateTime timestamp { get; set; }
        public Nullable<double> gps_latitude { get; set; }
        public Nullable<double> gps_longitude { get; set; }
        public Nullable<double> reading_A { get; set; }
    }
}
