//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_harpoon_employee
    {
        public string employee_id { get; set; }
        public string first_name { get; set; }
        public string middle_initial { get; set; }
        public string last_name { get; set; }
        public string position { get; set; }
        public Nullable<System.DateTime> Date_of_birth { get; set; }
        public string client_id { get; set; }
        public Nullable<int> status { get; set; }
        public byte[] profile_pic { get; set; }
        public Nullable<int> auto_loc_id { get; set; }
        public int auto_emp_id { get; set; }
    }
}
