//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_production_schedule
    {
        public int production_id { get; set; }
        public Nullable<int> priority { get; set; }
        public string size { get; set; }
        public string casing_spec { get; set; }
        public Nullable<bool> virgin { get; set; }
        public string tread { get; set; }
        public Nullable<System.DateTime> production_date { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> part_no { get; set; }
        public Nullable<int> quantity_complete { get; set; }
    }
}
