//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee_leave_annual_calculations
    {
        public int employee_id { get; set; }
        public Nullable<double> vacation_used { get; set; }
        public Nullable<double> sick_days_used { get; set; }
        public Nullable<double> paid_leave_used { get; set; }
        public Nullable<double> non_paid_leave_used { get; set; }
        public Nullable<double> group_insurance_used { get; set; }
        public Nullable<double> breavement_used { get; set; }
        public Nullable<double> employment_insurance_used { get; set; }
        public Nullable<double> workers_compensation_used { get; set; }
    }
}
