//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reporting_sales_labour_daily
    {
        public string loc_id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<double> mechanical_labour { get; set; }
        public Nullable<double> tire_labour { get; set; }
    }
}
