//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee_status
    {
        public int employee_id { get; set; }
        public Nullable<System.DateTime> date_of_joining { get; set; }
        public Nullable<System.DateTime> date_of_leaving { get; set; }
        public Nullable<double> vacation { get; set; }
        public Nullable<double> vacation_buyin { get; set; }
        public Nullable<double> sick_days { get; set; }
        public string compensation_type { get; set; }
    }
}
