//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_source_payrollDeductions_cpp
    {
        public string CPP_QPP { get; set; }
        public Nullable<double> YMPE { get; set; }
        public Nullable<double> Basic_Exemption { get; set; }
        public Nullable<double> Max_contributory_earnings_YMCE { get; set; }
        public Nullable<double> Employee_contribution_rate { get; set; }
        public Nullable<double> Employee_max_contribution { get; set; }
        public Nullable<double> Self_employed_max_contribution { get; set; }
        public Nullable<double> YMPE_before_rounding { get; set; }
    }
}
