//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_location_departments
    {
        public string loc_id { get; set; }
        public Nullable<bool> auto_tech { get; set; }
        public Nullable<bool> tire_tech { get; set; }
        public Nullable<bool> retread_tech { get; set; }
    }
}
