//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_source_treadtracker_freightSchedule_revision
    {
        public System.DateTime revision_date { get; set; }
        public double freight_004 { get; set; }
        public double freight_005 { get; set; }
        public double freight_007 { get; set; }
        public double freight_009 { get; set; }
        public double freight_010 { get; set; }
        public double freight_347 { get; set; }
    }
}
