//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_calculator_GM_parts
    {
        public double minimum_cost { get; set; }
        public double maximum_cost { get; set; }
        public Nullable<double> GrossMargin { get; set; }
        public Nullable<double> GrossMargin_NA { get; set; }
    }
}
