//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_source_payrollDeductions_ei
    {
        public string EI { get; set; }
        public Nullable<double> Annual_max_insurable_earnings { get; set; }
        public Nullable<double> Employee_contribution_rate { get; set; }
        public Nullable<double> Employer_contribution_rate { get; set; }
        public Nullable<double> Annual_max_employee_premium { get; set; }
        public Nullable<double> Annual_max_employer_premium { get; set; }
    }
}
