//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_harpoon_vehicle
    {
        public int vehicle_auto_id { get; set; }
        public string VIN { get; set; }
        public string vehicle_long_id { get; set; }
        public string plate { get; set; }
        public Nullable<int> auto_loc_id { get; set; }
        public string manufacturer { get; set; }
        public string model { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<bool> status { get; set; }
        public byte[] vehicle_image { get; set; }
        public byte[] thumbnail { get; set; }
        public Nullable<double> current_milage { get; set; }
        public Nullable<double> efficiency_price { get; set; }
        public Nullable<double> efficiency_liter { get; set; }
    }
}
