//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_source_treadtracker_consumables_nonTreadRubber
    {
        public string part_number { get; set; }
        public string description { get; set; }
        public string type { get; set; }
        public Nullable<bool> TT0300 { get; set; }
        public Nullable<bool> TT0400 { get; set; }
        public string measurement { get; set; }
        public Nullable<double> lb_per_ft { get; set; }
    }
}
