//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_treadtracker_inventory_casing
    {
        public string casing_size { get; set; }
        public Nullable<int> total_code_1 { get; set; }
        public Nullable<int> total_code_6 { get; set; }
        public Nullable<int> total_code_10 { get; set; }
        public Nullable<int> total_code_11 { get; set; }
    }
}
