//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_source_workStation_info
    {
        public string loc_id { get; set; }
        public string description { get; set; }
        public string anydesk { get; set; }
        public string password { get; set; }
        public string ip_address { get; set; }
    }
}
