//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_source_treadtracker_creditSchedule
    {
        public string casing_size { get; set; }
        public string cap_count { get; set; }
        public double credit_brand { get; set; }
        public Nullable<double> credit_nonBrand { get; set; }
    }
}
