//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee_payroll_final
    {
        public int payroll_id { get; set; }
        public int employee_id { get; set; }
        public string end_date { get; set; }
        public string location_id { get; set; }
        public string full_name { get; set; }
        public Nullable<double> CommissionPay_D { get; set; }
        public Nullable<double> StatutoryHolidayPay_H { get; set; }
        public Nullable<double> SalaryPay_D { get; set; }
        public Nullable<double> VacationPay_D { get; set; }
        public Nullable<double> RegularPay_H { get; set; }
        public Nullable<double> OvertimePay_H { get; set; }
        public Nullable<double> OvertimePay_2_H { get; set; }
        public Nullable<double> OtherPay_D { get; set; }
        public Nullable<double> SickLeave_H { get; set; }
        public Nullable<double> VacationTime_H { get; set; }
        public Nullable<double> OnCallCommission_D { get; set; }
        public Nullable<double> OvertimePay_3_H { get; set; }
    }
}
