//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_data_import_history
    {
        public string data_type { get; set; }
        public string performed_by { get; set; }
        public System.DateTime import_date { get; set; }
        public string comments { get; set; }
    }
}
