//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_treadTracker_chamber_senser
    {
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<double> slope { get; set; }
        public Nullable<double> intercept { get; set; }
        public Nullable<bool> status { get; set; }
        public string senser { get; set; }
    }
}
