//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_treadtracker_LineCode_PlantProcess
    {
        public int line_code { get; set; }
        public Nullable<bool> TT050 { get; set; }
        public Nullable<bool> TT100 { get; set; }
        public Nullable<bool> TT200 { get; set; }
        public Nullable<bool> TT300 { get; set; }
        public Nullable<bool> TT400 { get; set; }
        public Nullable<bool> TT500 { get; set; }
        public Nullable<bool> TT600 { get; set; }
    }
}
