//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee_payroll_submission
    {
        public string submission_id { get; set; }
        public int payroll_id { get; set; }
        public string location_id { get; set; }
        public int employee_id { get; set; }
        public string submitted_by { get; set; }
        public Nullable<System.DateTime> submission_date { get; set; }
        public Nullable<double> regular { get; set; }
        public Nullable<double> ot { get; set; }
        public Nullable<double> vacationTime { get; set; }
        public Nullable<double> sickTime { get; set; }
        public Nullable<double> StatutoryTime { get; set; }
        public Nullable<double> commission { get; set; }
        public Nullable<double> callCommission { get; set; }
        public Nullable<double> otherPay { get; set; }
        public Nullable<double> vacationPay { get; set; }
        public Nullable<double> adjustmentPay { get; set; }
        public Nullable<int> recordFlag { get; set; }
        public Nullable<double> PaidLeave { get; set; }
        public Nullable<double> NonPaidLeave { get; set; }
        public string adjustment_type { get; set; }
        public string compensation_type { get; set; }
        public string comments { get; set; }
        public string plus_minus { get; set; }
        public Nullable<double> adjustmentPay2 { get; set; }
        public string adjustment_type2 { get; set; }
        public string plus_minus2 { get; set; }
        public Nullable<double> adjustmentPay1 { get; set; }
        public string adjustment_type1 { get; set; }
        public string plus_minus1 { get; set; }
        public Nullable<double> adjustmentPay_validate { get; set; }
        public string adjustmentCategory_validate { get; set; }
        public string plus_minus_validate { get; set; }
        public Nullable<double> adjustmentPay_validate1 { get; set; }
        public string adjustmentCategory_validate1 { get; set; }
        public string plus_minus_validate1 { get; set; }
    }
}
