//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fleetTVT_fieldsurvey_tire
    {
        public string customer_number { get; set; }
        public string unit_number { get; set; }
        public System.DateTime survey_date { get; set; }
        public string position { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public string size { get; set; }
        public Nullable<double> new_32nds { get; set; }
        public Nullable<double> actual_32nds { get; set; }
        public Nullable<int> spec_psi { get; set; }
        public Nullable<int> actual_psi { get; set; }
        public string condition_wear { get; set; }
        public string valve { get; set; }
        public string condition_wheel { get; set; }
        public string condition_tire { get; set; }
        public string comments { get; set; }
    }
}
