//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_treadTracker_Envelope
    {
        public string envelope_id { get; set; }
        public Nullable<int> cure_count_total { get; set; }
        public string cure_count_service { get; set; }
    }
}
