//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_source_harpoon_timesheet_category_selection
    {
        public string client_id { get; set; }
        public Nullable<bool> Re { get; set; }
        public string Re_type { get; set; }
        public Nullable<bool> Ot { get; set; }
        public string Ot_type { get; set; }
        public Nullable<bool> Va { get; set; }
        public string Va_type { get; set; }
        public Nullable<bool> St { get; set; }
        public string St_type { get; set; }
        public Nullable<bool> Si { get; set; }
        public string Si_type { get; set; }
        public Nullable<bool> Pl { get; set; }
        public string Pl_type { get; set; }
        public Nullable<bool> Nl { get; set; }
        public string Nl_type { get; set; }
        public Nullable<bool> Br { get; set; }
        public string Br_type { get; set; }
        public string total { get; set; }
    }
}
