//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_source_RARcodes
    {
        public string code { get; set; }
        public string description { get; set; }
        public Nullable<int> TT050 { get; set; }
        public Nullable<int> TT100 { get; set; }
        public Nullable<int> TT200 { get; set; }
        public Nullable<int> TT400 { get; set; }
        public Nullable<int> TT600 { get; set; }
        public Nullable<int> TT300 { get; set; }
    }
}
