//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_source_treadtracker_creditSchedule_revision
    {
        public System.DateTime revision_date { get; set; }
        public int tire_id { get; set; }
        public double creditBrand_virgin { get; set; }
        public double creditBrand_capped1 { get; set; }
        public double creditBrand_capped2plus { get; set; }
        public double creditNonBrand_virgin { get; set; }
        public double creditNonBrand_capped1 { get; set; }
        public double creditNonBrand_capped2plus { get; set; }
        public Nullable<int> outDated_brand { get; set; }
        public Nullable<int> outDated_nonBrand { get; set; }
    }
}
