//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_harpoon_departments
    {
        public string auto_department_id { get; set; }
        public string department_name { get; set; }
        public string loc_id_pairing { get; set; }
        public string loc_id_installation { get; set; }
        public string client_id { get; set; }
    }
}
