//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_treadtracker_customer_retread_spec
    {
        public int customer_number { get; set; }
        public Nullable<int> age_limit { get; set; }
        public Nullable<bool> brand_name_only { get; set; }
        public Nullable<int> outdatedCasingValue { get; set; }
    }
}
