//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_harpoon_users
    {
        public string email { get; set; }
        public string password { get; set; }
        public string client_id { get; set; }
        public string profile { get; set; }
        public string loc_id { get; set; }
        public bool adminClocking_editTime { get; set; }
        public bool jobIDClocking { get; set; }
        public bool jobIDClocking_editTime { get; set; }
        public bool adminClocking { get; set; }
    }
}
