//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Efficiancy_Technician_Commissions
    {
        public int employee_id { get; set; }
        public string loc_id { get; set; }
        public string payroll_id { get; set; }
        public double door_rate { get; set; }
        public Nullable<double> commissionable_sales_due { get; set; }
        public string commission_plan { get; set; }
        public string commissions { get; set; }
    }
}
