//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tread_tracker_chamber_data_logger
    {
        public System.DateTime timestamp { get; set; }
        public Nullable<double> pressure_1 { get; set; }
        public Nullable<double> pressure_2 { get; set; }
        public Nullable<double> pressure_3 { get; set; }
        public Nullable<double> temperature_1 { get; set; }
        public Nullable<double> temperature_2 { get; set; }
        public Nullable<double> temperature_3 { get; set; }
        public Nullable<double> temperature_4 { get; set; }
    }
}
