//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_payroll_employee_specifications
    {
        public int emp_id { get; set; }
        public Nullable<double> payRat_per_hour { get; set; }
        public Nullable<double> federal_tax_exemption { get; set; }
        public Nullable<double> provincial_tax_exemption { get; set; }
        public Nullable<double> cpp_exemption { get; set; }
        public Nullable<double> group_ins { get; set; }
        public Nullable<bool> rrsp_voluntary { get; set; }
        public Nullable<double> pensionPlan_contribution { get; set; }
        public Nullable<double> pensionPlan_match { get; set; }
        public Nullable<double> pensionPlan_additional { get; set; }
        public Nullable<bool> ei_eligible { get; set; }
    }
}
