//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fleettvt_configurations
    {
        public string Type { get; set; }
        public string Configuration { get; set; }
        public Nullable<double> one_li { get; set; }
        public Nullable<double> one_lo { get; set; }
        public Nullable<double> one_ri { get; set; }
        public Nullable<double> one_ro { get; set; }
        public Nullable<double> two_li { get; set; }
        public Nullable<double> two_lo { get; set; }
        public Nullable<double> two_ri { get; set; }
        public Nullable<double> two_ro { get; set; }
        public Nullable<double> three_li { get; set; }
        public Nullable<double> three_lo { get; set; }
        public Nullable<double> three_ri { get; set; }
        public Nullable<double> three_ro { get; set; }
        public Nullable<double> four_li { get; set; }
        public Nullable<double> four_lo { get; set; }
        public Nullable<double> four_ri { get; set; }
        public Nullable<double> four_ro { get; set; }
        public Nullable<double> five_li { get; set; }
        public Nullable<double> five_lo { get; set; }
        public Nullable<double> five_ri { get; set; }
        public Nullable<double> five_ro { get; set; }
    }
}
