//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_harpoon_jobclock
    {
        public string jobclock_id { get; set; }
        public string name { get; set; }
        public Nullable<bool> available_to_all_locations { get; set; }
        public string parent_location { get; set; }
        public Nullable<bool> admin { get; set; }
        public string clocking_comments { get; set; }
        public string client_id { get; set; }
    }
}
