//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_login_log
    {
        public int log_id { get; set; }
        public string employee_id { get; set; }
        public Nullable<System.DateTime> time_stamp { get; set; }
        public string ip_address { get; set; }
    }
}
