//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_management_training
    {
        public int emp_id { get; set; }
        public string staff_member { get; set; }
        public Nullable<bool> first_aid { get; set; }
        public Nullable<bool> ohs { get; set; }
        public Nullable<int> tia { get; set; }
        public Nullable<bool> good_year { get; set; }
        public Nullable<bool> other { get; set; }
        public Nullable<System.DateTime> fa_aspiration_date { get; set; }
        public string fa_certificate { get; set; }
        public Nullable<System.DateTime> ohs_aspiration_date { get; set; }
        public string ohs_certificate { get; set; }
        public Nullable<System.DateTime> gy_aspiration_date { get; set; }
        public string gy_certificate { get; set; }
        public Nullable<System.DateTime> other_aspiration_date { get; set; }
        public string other_certificate { get; set; }
    }
}
