//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sehub_access
    {
        public int employee_id { get; set; }
        public Nullable<int> app_access { get; set; }
        public Nullable<int> dashboard { get; set; }
        public Nullable<int> calendar { get; set; }
        public Nullable<int> newsletter { get; set; }
        public Nullable<int> neworder { get; set; }
        public Nullable<int> openorder { get; set; }
        public Nullable<int> my_staff { get; set; }
        public Nullable<int> payroll { get; set; }
        public Nullable<int> attendance { get; set; }
        public Nullable<int> new_hire_package { get; set; }
        public Nullable<int> vacation_schedule { get; set; }
        public Nullable<int> asset_control { get; set; }
        public Nullable<int> calculator { get; set; }
        public Nullable<int> fuel_log { get; set; }
        public Nullable<int> library_access { get; set; }
        public Nullable<int> manufacturing_plant { get; set; }
        public Nullable<int> user_management { get; set; }
        public Nullable<int> customer_reporting { get; set; }
    }
}
