//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cta_customers
    {
        public int CustomerCode { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string CustomerName { get; set; }
        public string Fax { get; set; }
        public string Postcode { get; set; }
        public string Telephone { get; set; }
        public Nullable<bool> tread_tracker { get; set; }
        public Nullable<bool> call_reporting { get; set; }
        public Nullable<bool> fleet_tvt { get; set; }
    }
}
