//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee_payroll_summary
    {
        public int employee_id { get; set; }
        public int payroll_id { get; set; }
        public Nullable<double> regular { get; set; }
        public Nullable<double> ot { get; set; }
        public Nullable<double> vac { get; set; }
        public Nullable<double> sick { get; set; }
        public Nullable<double> brev { get; set; }
        public Nullable<int> record_flag { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<double> stat { get; set; }
        public Nullable<double> split { get; set; }
        public Nullable<double> gen_ins { get; set; }
        public Nullable<double> emp_ins { get; set; }
        public Nullable<double> workers_comp { get; set; }
    }
}
