//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cta_location_survey
    {
        public string loc_id { get; set; }
        public string employeeSurvey_link { get; set; }
        public string employeeSurvey_read { get; set; }
        public string customerSurvey_link { get; set; }
        public string customerSurvey_read { get; set; }
        public string commercialCustomerSurvey_link { get; set; }
        public string commercialCustomerSurvey_read { get; set; }
    }
}
