//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fleetTVT_unit
    {
        public string customer_number { get; set; }
        public string unit_number { get; set; }
        public string unit_name { get; set; }
        public Nullable<int> Active { get; set; }
        public string survey_type { get; set; }
        public string survey_configuration { get; set; }
        public string short_description { get; set; }
        public Nullable<int> mileage { get; set; }
        public Nullable<double> hours { get; set; }
        public Nullable<int> year { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public string plate_number { get; set; }
        public Nullable<double> length { get; set; }
        public Nullable<System.DateTime> date_expired { get; set; }
        public string other { get; set; }
        public Nullable<double> spec_psi_1 { get; set; }
        public Nullable<double> spec_psi_2 { get; set; }
        public Nullable<double> spec_psi_3 { get; set; }
        public string VIN { get; set; }
        public Nullable<System.DateTime> last_survey { get; set; }
        public byte[] unit_image { get; set; }
        public string tire_size_1 { get; set; }
        public string tire_size_2 { get; set; }
        public string tire_size_3 { get; set; }
    }
}
