//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLocationBkp
    {
        public string locID { get; set; }
        public string locDESCRIPTION { get; set; }
        public string locNONSIG { get; set; }
        public string locPHONE { get; set; }
        public string locFAX { get; set; }
        public string loc24HOUR { get; set; }
        public string addressSTREET1 { get; set; }
        public string addressSTREET2 { get; set; }
        public string addressCITY { get; set; }
        public string addressPROVINCE { get; set; }
        public string addressPOSTAL { get; set; }
        public string addressCOUNTRY { get; set; }
    }
}
