//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeHubPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServiceEstimate_new
    {
        public string EstimateID { get; set; }
        public int FullName { get; set; }
        public System.DateTime DevelopmentDate { get; set; }
        public string CustomerCompany { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string JobID { get; set; }
        public Nullable<double> Mileage { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> HST { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> QTY1 { get; set; }
        public Nullable<double> QTY2 { get; set; }
        public Nullable<double> QTY3 { get; set; }
        public Nullable<double> QTY4 { get; set; }
        public Nullable<double> QTY5 { get; set; }
        public Nullable<double> QTY6 { get; set; }
        public Nullable<double> QTY7 { get; set; }
        public Nullable<double> QTY8 { get; set; }
        public Nullable<double> QTY9 { get; set; }
        public Nullable<double> QTY10 { get; set; }
        public Nullable<double> QTY11 { get; set; }
        public Nullable<double> QTY12 { get; set; }
        public Nullable<double> QTY13 { get; set; }
        public Nullable<double> QTY14 { get; set; }
        public Nullable<double> QTY15 { get; set; }
        public Nullable<double> QTY16 { get; set; }
        public Nullable<double> QTY17 { get; set; }
        public Nullable<double> QTY18 { get; set; }
        public Nullable<double> QTY19 { get; set; }
        public Nullable<double> QTY20 { get; set; }
        public Nullable<double> QTY21 { get; set; }
        public Nullable<double> QTY22 { get; set; }
        public Nullable<double> QTY23 { get; set; }
        public Nullable<double> QTY24 { get; set; }
        public Nullable<double> QTY25 { get; set; }
        public Nullable<double> QTY26 { get; set; }
        public Nullable<double> QTY27 { get; set; }
        public Nullable<double> QTY28 { get; set; }
        public Nullable<double> QTY29 { get; set; }
        public Nullable<double> QTY30 { get; set; }
        public Nullable<double> QTY31 { get; set; }
        public Nullable<double> QTY32 { get; set; }
        public Nullable<double> QTY33 { get; set; }
        public Nullable<double> QTY34 { get; set; }
        public Nullable<double> QTY35 { get; set; }
        public Nullable<double> QTY36 { get; set; }
        public Nullable<double> QTY37 { get; set; }
        public Nullable<double> QTY38 { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public string Description4 { get; set; }
        public string Description5 { get; set; }
        public string Description6 { get; set; }
        public string Description7 { get; set; }
        public string Description8 { get; set; }
        public string Description9 { get; set; }
        public string Description10 { get; set; }
        public string Description11 { get; set; }
        public string Description12 { get; set; }
        public string Description13 { get; set; }
        public string Description14 { get; set; }
        public string Description15 { get; set; }
        public string Description16 { get; set; }
        public string Description17 { get; set; }
        public string Description18 { get; set; }
        public string Description19 { get; set; }
        public string Description20 { get; set; }
        public string Description21 { get; set; }
        public string Description22 { get; set; }
        public string Description23 { get; set; }
        public string Description24 { get; set; }
        public string Description25 { get; set; }
        public string Description26 { get; set; }
        public string Description27 { get; set; }
        public string Description28 { get; set; }
        public string Description29 { get; set; }
        public string Description30 { get; set; }
        public string Description31 { get; set; }
        public string Description32 { get; set; }
        public string Description33 { get; set; }
        public string Description34 { get; set; }
        public string Description35 { get; set; }
        public string Description36 { get; set; }
        public string Description37 { get; set; }
        public string Description38 { get; set; }
        public Nullable<double> UnitPrice1 { get; set; }
        public Nullable<double> UnitPrice2 { get; set; }
        public Nullable<double> UnitPrice3 { get; set; }
        public Nullable<double> UnitPrice4 { get; set; }
        public Nullable<double> UnitPrice5 { get; set; }
        public Nullable<double> UnitPrice6 { get; set; }
        public Nullable<double> UnitPrice7 { get; set; }
        public Nullable<double> UnitPrice8 { get; set; }
        public Nullable<double> UnitPrice9 { get; set; }
        public Nullable<double> UnitPrice10 { get; set; }
        public Nullable<double> UnitPrice11 { get; set; }
        public Nullable<double> UnitPrice12 { get; set; }
        public Nullable<double> UnitPrice13 { get; set; }
        public Nullable<double> UnitPrice14 { get; set; }
        public Nullable<double> UnitPrice15 { get; set; }
        public Nullable<double> UnitPrice16 { get; set; }
        public Nullable<double> UnitPrice17 { get; set; }
        public Nullable<double> UnitPrice18 { get; set; }
        public Nullable<double> UnitPrice19 { get; set; }
        public Nullable<double> UnitPrice20 { get; set; }
        public Nullable<double> UnitPrice21 { get; set; }
        public Nullable<double> UnitPrice22 { get; set; }
        public Nullable<double> UnitPrice23 { get; set; }
        public Nullable<double> UnitPrice24 { get; set; }
        public Nullable<double> UnitPrice25 { get; set; }
        public Nullable<double> UnitPrice26 { get; set; }
        public Nullable<double> UnitPrice27 { get; set; }
        public Nullable<double> UnitPrice28 { get; set; }
        public Nullable<double> UnitPrice29 { get; set; }
        public Nullable<double> UnitPrice30 { get; set; }
        public Nullable<double> UnitPrice31 { get; set; }
        public Nullable<double> UnitPrice32 { get; set; }
        public Nullable<double> UnitPrice33 { get; set; }
        public Nullable<double> UnitPrice34 { get; set; }
        public Nullable<double> UnitPrice35 { get; set; }
        public Nullable<double> UnitPrice36 { get; set; }
        public Nullable<double> UnitPrice37 { get; set; }
        public Nullable<double> UnitPrice38 { get; set; }
    }
}
